name: Build, Push Docker Image, and Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Trigger on push to the `main` branch
    tags:
      - 'v*.*.*'  # Trigger on version tags
  pull_request:
    branches:
      - main  # Optionally, trigger for PRs to the `main` branch

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository code
      - name: Check out repository
        uses: actions/checkout@v2

      # Step 2: Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 3: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 4: Get the short commit SHA and Git tag
      - name: Get short commit SHA
        id: sha
        run: echo "SHORT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Get Git tag
        id: tag
        run: |
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            echo "VERSION_TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
          else
            echo "VERSION_TAG=latest" >> $GITHUB_ENV
          fi

      # Step 5: Build and push Docker image
      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: |
            sahildhillon0/react-app:latest
            sahildhillon0/react-app:${{ env.VERSION_TAG }}
            sahildhillon0/react-app:${{ env.SHORT_SHA }}

      # Step 6: Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Use the version of Node.js you're using

      # Step 7: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 8: Build the app
      - name: Build
        run: npm run build

      # Step 9: Deploy to GitHub Pages (will create 'gh-pages' branch)
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_PAT }}
          publish_dir: ./dist
