name: Docker Image CI and Deploy to GitHub Pages

on: 
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'

permissions:
  contents: write      
  pages: write         
  id-token: read       

jobs: 
  build_and_publish: 
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository code
      - uses: actions/checkout@v3

      # Step 2: Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 3: Log in to GitHub Container Registry
      - name: Log in to GitHub Container Registry
        run: |
          echo ${{ secrets.GH_PAT }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      # Step 4: Get short commit SHA
      - name: Get short commit SHA
        id: sha
        run: echo "SHORT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      # Step 5: Get Git tag if it exists, otherwise use 'latest'
      - name: Get Git tag
        id: tag
        run: |
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            echo "VERSION_TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
          else
            echo "VERSION_TAG=latest" >> $GITHUB_ENV
          fi

      # Step 6: Build and push Docker image
      - name: Build and push Docker image
        run: |
          docker build . --tag ghcr.io/sahildhillon0/amazon_smb:latest --tag ghcr.io/sahildhillon0/amazon_smb:${{ env.VERSION_TAG }} --tag ghcr.io/sahildhillon0/amazon_smb:${{ env.SHORT_SHA }}
          docker push ghcr.io/sahildhillon0/amazon_smb:latest
          docker push ghcr.io/sahildhillon0/amazon_smb:${{ env.VERSION_TAG }}
          docker push ghcr.io/sahildhillon0/amazon_smb:${{ env.SHORT_SHA }}

      # Step 7: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist  # Adjust this if your static files are in a different folder
